//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TESTVS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Import
    {
        public string AccountantId { get; set; }
        public string GoodsId { get; set; }
        public string GoodsUnit { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public System.DateTime ImportDate { get; set; }
    
        public virtual Accountant Accountant { get; set; }
        public virtual Good Good { get; set; }
    }
}
